/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vdalton;

/**
 *
 * @author Beto
 */
public class test1 extends javax.swing.JFrame {
    
    VDalton vd = new VDalton();
    resultado configuracion = new resultado();
    /**
     * Creates new form asda
     */
    public test1() {
        initComponents();
        this.nombre.setText(vd.usuario);
        this.setLocationRelativeTo(null);
        this.setIconImage(vd.imageicon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        P1 = new javax.swing.ButtonGroup();
        P2 = new javax.swing.ButtonGroup();
        P3 = new javax.swing.ButtonGroup();
        P4 = new javax.swing.ButtonGroup();
        P5 = new javax.swing.ButtonGroup();
        P6 = new javax.swing.ButtonGroup();
        P7 = new javax.swing.ButtonGroup();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        n29 = new javax.swing.JRadioButton();
        n70 = new javax.swing.JRadioButton();
        nada = new javax.swing.JRadioButton();
        contenedor1 = new javax.swing.JLabel();
        listo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        n71 = new javax.swing.JRadioButton();
        n30 = new javax.swing.JRadioButton();
        nada1 = new javax.swing.JRadioButton();
        contenedor = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        nada2 = new javax.swing.JRadioButton();
        n72 = new javax.swing.JRadioButton();
        n31 = new javax.swing.JRadioButton();
        contenedor2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        nada3 = new javax.swing.JRadioButton();
        n73 = new javax.swing.JRadioButton();
        n32 = new javax.swing.JRadioButton();
        contenedor3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        nada4 = new javax.swing.JRadioButton();
        n33 = new javax.swing.JRadioButton();
        contenedor4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        nada5 = new javax.swing.JRadioButton();
        n75 = new javax.swing.JRadioButton();
        n34 = new javax.swing.JRadioButton();
        contenedor5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nada6 = new javax.swing.JRadioButton();
        n76 = new javax.swing.JRadioButton();
        n35 = new javax.swing.JRadioButton();
        contenedor6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        regresar = new javax.swing.JButton();
        nombre = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VDalton Beta 1.0");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/indicaciones.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 12, -1, -1));

        P1.add(n29);
        n29.setBorder(null);
        n29.setContentAreaFilled(false);
        n29.setFocusPainted(false);
        n29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/respuestas/29.png"))); // NOI18N
        n29.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/respuestas/29_S.png"))); // NOI18N
        jPanel1.add(n29, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        P1.add(n70);
        n70.setBorder(null);
        n70.setContentAreaFilled(false);
        n70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/respuestas/70.png"))); // NOI18N
        n70.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/respuestas/70_S.png"))); // NOI18N
        jPanel1.add(n70, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));

        P1.add(nada);
        nada.setBorder(null);
        nada.setContentAreaFilled(false);
        nada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/respuestas/nada.png"))); // NOI18N
        nada.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/respuestas/nada_S.png"))); // NOI18N
        nada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nadaActionPerformed(evt);
            }
        });
        jPanel1.add(nada, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        contenedor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/contenedor.png"))); // NOI18N
        jPanel1.add(contenedor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 260, 198));

        listo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/listo.png"))); // NOI18N
        listo.setBorder(null);
        listo.setBorderPainted(false);
        listo.setContentAreaFilled(false);
        listo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/listo_s.png"))); // NOI18N
        listo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listoActionPerformed(evt);
            }
        });
        jPanel1.add(listo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 1900, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/29.1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 190, 200));

        P2.add(n71);
        n71.setBorder(null);
        n71.setContentAreaFilled(false);
        n71.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/respuestas/10.png"))); // NOI18N
        n71.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/respuestas/10_s.png"))); // NOI18N
        jPanel1.add(n71, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, -1, -1));

        P2.add(n30);
        n30.setBorder(null);
        n30.setContentAreaFilled(false);
        n30.setFocusPainted(false);
        n30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/respuestas/12.png"))); // NOI18N
        n30.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/respuestas/12_s.png"))); // NOI18N
        jPanel1.add(n30, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, -1, -1));

        P2.add(nada1);
        nada1.setBorder(null);
        nada1.setContentAreaFilled(false);
        nada1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/respuestas/nada.png"))); // NOI18N
        nada1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/respuestas/nada_S.png"))); // NOI18N
        nada1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nada1ActionPerformed(evt);
            }
        });
        jPanel1.add(nada1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, -1, -1));

        contenedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/contenedor.png"))); // NOI18N
        jPanel1.add(contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 260, 198));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 590, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 590, 10));

        P3.add(nada2);
        nada2.setBorder(null);
        nada2.setContentAreaFilled(false);
        nada2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/respuestas/nada.png"))); // NOI18N
        nada2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/respuestas/nada_S.png"))); // NOI18N
        nada2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nada2ActionPerformed(evt);
            }
        });
        jPanel1.add(nada2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 740, -1, -1));

        P3.add(n72);
        n72.setBorder(null);
        n72.setContentAreaFilled(false);
        n72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/respuestas/3.png"))); // NOI18N
        n72.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/respuestas/3_s.png"))); // NOI18N
        jPanel1.add(n72, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 690, -1, -1));

        P3.add(n31);
        n31.setBorder(null);
        n31.setContentAreaFilled(false);
        n31.setFocusPainted(false);
        n31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/respuestas/8.png"))); // NOI18N
        n31.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/respuestas/8_s.png"))); // NOI18N
        jPanel1.add(n31, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 640, -1, -1));

        contenedor2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/contenedor.png"))); // NOI18N
        jPanel1.add(contenedor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 600, 260, 198));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/8.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, 190, 200));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 830, 590, 10));

        P4.add(nada3);
        nada3.setBorder(null);
        nada3.setContentAreaFilled(false);
        nada3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/respuestas/nada.png"))); // NOI18N
        nada3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/respuestas/nada_S.png"))); // NOI18N
        nada3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nada3ActionPerformed(evt);
            }
        });
        jPanel1.add(nada3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 1000, -1, -1));

        P4.add(n73);
        n73.setBorder(null);
        n73.setContentAreaFilled(false);
        n73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/respuestas/5.png"))); // NOI18N
        n73.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/respuestas/5_s.png"))); // NOI18N
        jPanel1.add(n73, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 950, -1, -1));

        P4.add(n32);
        n32.setBorder(null);
        n32.setContentAreaFilled(false);
        n32.setFocusPainted(false);
        n32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/respuestas/6.png"))); // NOI18N
        n32.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/respuestas/6_s.png"))); // NOI18N
        jPanel1.add(n32, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 900, -1, -1));

        contenedor3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/contenedor.png"))); // NOI18N
        jPanel1.add(contenedor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 860, 260, 198));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/4.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 840, 200, 220));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1090, 590, 10));

        P5.add(nada4);
        nada4.setBorder(null);
        nada4.setContentAreaFilled(false);
        nada4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/respuestas/nada.png"))); // NOI18N
        nada4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/respuestas/nada_S.png"))); // NOI18N
        nada4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nada4ActionPerformed(evt);
            }
        });
        jPanel1.add(nada4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 1220, -1, -1));

        P5.add(n33);
        n33.setBorder(null);
        n33.setContentAreaFilled(false);
        n33.setFocusPainted(false);
        n33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/respuestas/6.png"))); // NOI18N
        n33.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/respuestas/6_s.png"))); // NOI18N
        jPanel1.add(n33, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 1160, -1, -1));

        contenedor4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/contenedor.png"))); // NOI18N
        jPanel1.add(contenedor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 1110, 260, 198));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/11.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1110, 190, 200));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1340, 590, 10));

        P6.add(nada5);
        nada5.setBorder(null);
        nada5.setContentAreaFilled(false);
        nada5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/respuestas/nada.png"))); // NOI18N
        nada5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/respuestas/nada_S.png"))); // NOI18N
        nada5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nada5ActionPerformed(evt);
            }
        });
        jPanel1.add(nada5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 1500, -1, -1));

        P6.add(n75);
        n75.setBorder(null);
        n75.setContentAreaFilled(false);
        n75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/respuestas/linea1.png"))); // NOI18N
        n75.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/respuestas/linea1_s.png"))); // NOI18N
        jPanel1.add(n75, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 1450, -1, -1));

        P6.add(n34);
        n34.setBorder(null);
        n34.setContentAreaFilled(false);
        n34.setFocusPainted(false);
        n34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/respuestas/linea.png"))); // NOI18N
        n34.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/respuestas/liena_s.png"))); // NOI18N
        jPanel1.add(n34, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 1400, -1, -1));

        contenedor5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/contenedor.png"))); // NOI18N
        jPanel1.add(contenedor5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 1360, 260, 198));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/35.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1360, 190, 200));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1590, 590, 10));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/37.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1620, 190, 200));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/12.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 190, 200));

        P7.add(nada6);
        nada6.setBorder(null);
        nada6.setContentAreaFilled(false);
        nada6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/respuestas/nada.png"))); // NOI18N
        nada6.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/respuestas/nada_S.png"))); // NOI18N
        nada6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nada6ActionPerformed(evt);
            }
        });
        jPanel1.add(nada6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 1760, -1, -1));

        P7.add(n76);
        n76.setBorder(null);
        n76.setContentAreaFilled(false);
        n76.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/respuestas/linea3.png"))); // NOI18N
        n76.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/respuestas/linea3_s.png"))); // NOI18N
        jPanel1.add(n76, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 1710, -1, -1));

        P7.add(n35);
        n35.setBorder(null);
        n35.setContentAreaFilled(false);
        n35.setFocusPainted(false);
        n35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/respuestas/linea2.png"))); // NOI18N
        n35.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/respuestas/linea2_s.png"))); // NOI18N
        jPanel1.add(n35, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 1660, -1, -1));

        contenedor6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/contenedor.png"))); // NOI18N
        jPanel1.add(contenedor6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 1620, 260, 198));

        jScrollPane3.setViewportView(jPanel1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 657, 390));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ishihara/titulo.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/regresar.png"))); // NOI18N
        regresar.setBorder(null);
        regresar.setContentAreaFilled(false);
        regresar.setFocusPainted(false);
        regresar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/regresar_s.png"))); // NOI18N
        regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regresarMouseClicked(evt);
            }
        });
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        getContentPane().add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 80, -1, -1));

        nombre.setBackground(new java.awt.Color(0, 0, 0));
        nombre.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nombre.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 35, 60, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/usuario.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 30, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/fondo.jpeg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listoActionPerformed
        // TODO add your handling code here:
        configuracion.setVisible(true);
        dispose();
    }//GEN-LAST:event_listoActionPerformed

    private void regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_regresarMouseClicked

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        // TODO add your handling code here:
        seleccion_test obj = new seleccion_test();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_regresarActionPerformed

    private void nadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nadaActionPerformed

    private void nada1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nada1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nada1ActionPerformed

    private void nada2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nada2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nada2ActionPerformed

    private void nada3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nada3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nada3ActionPerformed

    private void nada4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nada4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nada4ActionPerformed

    private void nada5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nada5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nada5ActionPerformed

    private void nada6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nada6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nada6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new test1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup P1;
    private javax.swing.ButtonGroup P2;
    private javax.swing.ButtonGroup P3;
    private javax.swing.ButtonGroup P4;
    private javax.swing.ButtonGroup P5;
    private javax.swing.ButtonGroup P6;
    private javax.swing.ButtonGroup P7;
    private javax.swing.JLabel contenedor;
    private javax.swing.JLabel contenedor1;
    private javax.swing.JLabel contenedor2;
    private javax.swing.JLabel contenedor3;
    private javax.swing.JLabel contenedor4;
    private javax.swing.JLabel contenedor5;
    private javax.swing.JLabel contenedor6;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JButton listo;
    private javax.swing.JRadioButton n29;
    private javax.swing.JRadioButton n30;
    private javax.swing.JRadioButton n31;
    private javax.swing.JRadioButton n32;
    private javax.swing.JRadioButton n33;
    private javax.swing.JRadioButton n34;
    private javax.swing.JRadioButton n35;
    private javax.swing.JRadioButton n70;
    private javax.swing.JRadioButton n71;
    private javax.swing.JRadioButton n72;
    private javax.swing.JRadioButton n73;
    private javax.swing.JRadioButton n75;
    private javax.swing.JRadioButton n76;
    private javax.swing.JRadioButton nada;
    private javax.swing.JRadioButton nada1;
    private javax.swing.JRadioButton nada2;
    private javax.swing.JRadioButton nada3;
    private javax.swing.JRadioButton nada4;
    private javax.swing.JRadioButton nada5;
    private javax.swing.JRadioButton nada6;
    private javax.swing.JLabel nombre;
    private javax.swing.JButton regresar;
    // End of variables declaration//GEN-END:variables
}
