/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vdalton;

import com.sun.awt.AWTUtilities;
import java.awt.AWTException;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.applet.AudioClip;
import javax.swing.JOptionPane;



/**
 *
 * @author Beto
 */
public final class Bienvenida extends javax.swing.JFrame  implements Runnable{
    Inicio nv = new Inicio();
    private Thread tiempo;

    /**
     * Creates new form bienvenida
     * @throws java.awt.AWTException
     */
    public Bienvenida() throws AWTException {
        initComponents();
        AWTUtilities.setWindowOpaque(this, false);
        this.setIconImage(nv.imageicon.getImage());
        this.setLocationRelativeTo(null);
        tiempo= new  Thread(this);
        tiempo.start();
        AudioClip sonido;
        sonido=java.applet.Applet.newAudioClip(getClass().getResource("/Test1/Ring08.wav"));
        sonido.play();
    }
    
 
    public static int getJavaHome() {
        File jv = new File("C:/Program Files/Java");
        if(jv.exists()){
        return 0;
        }else{
        return 1;
        }   
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Test1/logo_blanco.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        Resultado iniciado =new Resultado();
        File consulta =new File("C:/VDalton");
        java.awt.EventQueue.invokeLater(() -> {
        if(0==getJavaHome()){
        
            try {
                if(consulta.exists()) {
                    iniciado.Registro();
                    iniciado.cargarDatos();
                } else {
                    new Bienvenida().setVisible(true);
                }
                
            } catch (AWTException | IOException ex) {
                Logger.getLogger(Bienvenida.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
        JOptionPane.showMessageDialog(null, "No se encontro java instalado.\nPor favor instalalo https://www.java.com/es/download/");
        }
        });       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while(tiempo!=null){
            try {
                Thread.sleep(5000);
                this.dispose();
                new Inicio().setVisible(true);
                Thread.sleep(5000);
            } catch (InterruptedException ex) {
                Logger.getLogger(Bienvenida.class.getName()).log(Level.SEVERE, null, ex);
            }
            tiempo=null;
        }
//To change body of generated methods, choose Tools | Templates.
    
    }
}
