/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vdalton;


/**
 *
 * @author Beto
 */
public class Inicio extends javax.swing.JFrame{
 
    
   VDalton vd= new VDalton();

    /**
     * Creates new form Inicio
     */
    
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        user.setText(vd.usuario);
        this.setIconImage(vd.imageicon.getImage());    
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comenzar = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VDalton Beta 1.0");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comenzar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/boton.png"))); // NOI18N
        comenzar.setToolTipText("");
        comenzar.setBorder(null);
        comenzar.setBorderPainted(false);
        comenzar.setContentAreaFilled(false);
        comenzar.setFocusPainted(false);
        comenzar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/boton_press.png"))); // NOI18N
        comenzar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comenzarMouseClicked(evt);
            }
        });
        getContentPane().add(comenzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, -1, -1));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bitmap.png"))); // NOI18N
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 200, 200));

        user.setBackground(new java.awt.Color(255, 226, 188));
        user.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        user.setForeground(new java.awt.Color(85, 84, 82));
        user.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        user.setBorder(null);
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 260, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/fondo.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comenzarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comenzarMouseClicked
        // TODO add your handling code here:
        seleccion_test obj = new seleccion_test();
        obj.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_comenzarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Inicio().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JButton comenzar;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
