/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vdalton;



/**
 *
 * @author Beto
 */
public class seleccion_test extends javax.swing.JFrame {
    Inicio vd= new Inicio();
    
    public seleccion_test() {
        initComponents();
        nombre.setText(vd.usuario);
        setLocationRelativeTo(null);
        setIconImage(vd.imageicon.getImage());
         this.jButton1.setToolTipText("Minimizar");
         this.jButton2.setToolTipText("Cerrar");
         this.jButton3.setToolTipText("Regresar");
    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        indicacion = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        t1 = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        t2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        test1 = new javax.swing.JButton();
        test2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VDalton Beta 1.0");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        indicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Escoger_test/titulo_escogetest.png"))); // NOI18N
        getContentPane().add(indicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        nombre.setBackground(new java.awt.Color(255, 255, 255));
        nombre.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, 80, 30));

        t1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Escoger_test/titulo_test1.png"))); // NOI18N
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantalla_Principal/icono_usuario.png"))); // NOI18N
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 60, 60, 60));

        t2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Escoger_test/titulo_test2.png"))); // NOI18N
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Escoger_test/boton_minimize.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Escoger_test/boton_minimize_press.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, -1, 50));

        test1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Escoger_test/boton_queves.png"))); // NOI18N
        test1.setBorder(null);
        test1.setBorderPainted(false);
        test1.setContentAreaFilled(false);
        test1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        test1.setFocusPainted(false);
        test1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Escoger_test/boton_queves_press.png"))); // NOI18N
        test1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Escoger_test/boton_queves_press.png"))); // NOI18N
        test1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                test1MousePressed(evt);
            }
        });
        getContentPane().add(test1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 400, 100));

        test2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Escoger_test/boton_color.png"))); // NOI18N
        test2.setBorder(null);
        test2.setBorderPainted(false);
        test2.setContentAreaFilled(false);
        test2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        test2.setFocusPainted(false);
        test2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Escoger_test/boton_color_press.png"))); // NOI18N
        test2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Escoger_test/boton_color_press.png"))); // NOI18N
        test2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                test2MousePressed(evt);
            }
        });
        getContentPane().add(test2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 390, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Escoger_test/barra_separadora.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 540, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Escoger_test/cuadro_traslucido.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 600, 430));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Escoger_test/boton_cerrar.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Escoger_test/boton_cerrar_press.png"))); // NOI18N
        jButton2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Escoger_test/boton_cerrar_press.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, -1, 50));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Escoger_test/boton_atras.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Escoger_test/boton_atras_press.png"))); // NOI18N
        jButton3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Escoger_test/boton_atras_press.png"))); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Escoger_test/fondo_sinbotones.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
        // TODO add your handling code here:
        vd.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3MousePressed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_jButton2MousePressed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jButton1MousePressed

    private void test1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test1MousePressed
        // TODO add your handling code here:
        test1 obj = new test1();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_test1MousePressed

    private void test2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test2MousePressed
        // TODO add your handling code here:
        test2 vinculo = new test2();
        vinculo.setVisible(true);
        dispose();
    }//GEN-LAST:event_test2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seleccion_test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seleccion_test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seleccion_test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seleccion_test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new seleccion_test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel indicacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel t1;
    private javax.swing.JLabel t2;
    private javax.swing.JButton test1;
    private javax.swing.JButton test2;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables

}